
        ID MEMBER_NAME                              MEMBER_UNIQUE_NAME                                                                                 M M LEVEL_NAME   HIER_ORDER      DEPTH    IS_LEAF PARENT_LEVEL PARENT_UNIQUE_NAME                                                                                 BOX_OFFICE
---------- ---------------------------------------- -------------------------------------------------------------------------------------------------- - - ------------ ---------- ---------- ---------- ------------ -------------------------------------------------------------------------------------------------- ----------
           ALL SERIALS                              [ALL].[ALL SERIALS]                                                                                    ALL                   0          0          0                                                                                                                 4.2284E+10
         1 1                                        [SERIALS_LIST].&[1]                                                                                    SERIALS_LIST          1          1          1 ALL          [ALL].[ALL SERIALS]                                                                                 450000000
         2 2                                        [SERIALS_LIST].&[2]                                                                                    SERIALS_LIST          2          1          1 ALL          [ALL].[ALL SERIALS]                                                                                   9285714
         3 3                                        [SERIALS_LIST].&[3]                                                                                    SERIALS_LIST          3          1          1 ALL          [ALL].[ALL SERIALS]                                                                                  11500000
         4 4                                        [SERIALS_LIST].&[4]                                                                                    SERIALS_LIST          4          1          1 ALL          [ALL].[ALL SERIALS]                                                                                 823000000
         5 5                                        [SERIALS_LIST].&[5]                                                                                    SERIALS_LIST          5          1          1 ALL          [ALL].[ALL SERIALS]                                                                                4.0750E+10
         6 6                                        [SERIALS_LIST].&[6]                                                                                    SERIALS_LIST          6          1          1 ALL          [ALL].[ALL SERIALS]                                                                                 240000000

7 rows selected. 

