
        ID PRODUCTION_NAME                MEMBER_NAME                              MEMBER_UNIQUE_NAME                                                                                  M M LEVEL_NAME      HIER_ORDER      DEPTH    IS_LEAF PARENT_LEVEL_NA PARENT_UNIQUE_NAME                                                                                 
---------- ------------------------------ ---------------------------------------- --------------------------------------------------------------------------------------------------- - - --------------- ---------- ---------- ---------- --------------- ---------------------------------------------------------------------------------------------------
                                          ALL                                      [ALL].[ALL]                                                                                             ALL                      0          0          0                                                                                                                    
           BBC Television Centre          BBC Television Centre                    [PRODUCTION_NAME].&[BBC Television Centre]                                                              PRODUCTION_NAME          1          1          0 ALL             [ALL].[ALL]                                                                                        
         4 BBC Television Centre          4                                        [PRODUCTION_ID].&[4]                                                                                    PRODUCTION_ID            2          2          1 PRODUCTION_NAME [PRODUCTION_NAME].&[BBC Television Centre]                                                         
           Home Box Office (HBO)          Home Box Office (HBO)                    [PRODUCTION_NAME].&[Home Box Office (HBO)]                                                              PRODUCTION_NAME          3          1          0 ALL             [ALL].[ALL]                                                                                        
         5 Home Box Office (HBO)          5                                        [PRODUCTION_ID].&[5]                                                                                    PRODUCTION_ID            4          2          1 PRODUCTION_NAME [PRODUCTION_NAME].&[Home Box Office (HBO)]                                                         
           Yellow, Black production       Yellow, Black production                 [PRODUCTION_NAME].&[Yellow, Black production]                                                           PRODUCTION_NAME          5          1          0 ALL             [ALL].[ALL]                                                                                        
         1 Yellow, Black production       1                                        [PRODUCTION_ID].&[1]                                                                                    PRODUCTION_ID            6          2          1 PRODUCTION_NAME [PRODUCTION_NAME].&[Yellow, Black production]                                                      
           Гуд Стори Медиа                Гуд Стори Медиа                          [PRODUCTION_NAME].&[Гуд Стори Медиа]                                                                    PRODUCTION_NAME          7          1          0 ALL             [ALL].[ALL]                                                                                        
         2 Гуд Стори Медиа                2                                        [PRODUCTION_ID].&[2]                                                                                    PRODUCTION_ID            8          2          1 PRODUCTION_NAME [PRODUCTION_NAME].&[Гуд Стори Медиа]                                                               
           Среда                          Среда                                    [PRODUCTION_NAME].&[Среда]                                                                              PRODUCTION_NAME          9          1          0 ALL             [ALL].[ALL]                                                                                        
         3 Среда                          3                                        [PRODUCTION_ID].&[3]                                                                                    PRODUCTION_ID           10          2          1 PRODUCTION_NAME [PRODUCTION_NAME].&[Среда]                                                                         

11 rows selected. 
